modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
[[mods]]
modId="hvvisuals"
version="1.0.0"
displayName="HVVisuals"
logoFile="hvvisuals.png"
credits="Создано тобой"
authors="Твой Ник"
description='''
Визуальные улучшения для Minecraft 1.16.5 Forge.
- Отображение координат
- Прочность оружия
- Время суток
- Броня
- Звук при попадании
- Toggle Sprint (R)
- Low Fire
'''

[[dependencies.hvvisuals]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.hvvisuals]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
